### ISSUE TITLE
Potential issue with aggregation result (std deviation and variance)

### ISSUE THREAD

**Issue by Imisrael** [griddb/python_client#25]
I am running a query against the following dataset: https://www.kaggle.com/datasets/census/population-time-series-data. 

Here is the code: 

```
year_in_mili = 31536000000

ts = store.get_container("population")
query = ts.query("select * from population where value > 280000")
rs = query.fetch()

data = rs.next()
timestamp = calendar.timegm(data[0].timetuple())
gsTS = (griddb.TimestampUtils.get_time_millis(timestamp))
time = datetime.datetime.fromtimestamp(gsTS/1000.0)

added = gsTS + (year_in_mili * 7)
addedTime = datetime.datetime.fromtimestamp(added/1000.0)

variance = ts.aggregate_time_series(time, addedTime, griddb.Aggregation.VARIANCE, "value")
print("VARIANCE: ", variance.get(griddb.Type.DOUBLE))

stdDev = ts.aggregate_time_series(time, addedTime, griddb.Aggregation.STANDARD_DEVIATION, "value")
print("STANDARD DEVIATION: ", stdDev.get(griddb.Type.LONG))
```

The results for all are correct except for stdDev and variance

```
TOTAL:  48714984
AVERAGE:  289970
VARIANCE:  -84078718183.5204
STANDARD DEVIATION:  -9223372036854775808
COUNT  168
WEIGHTED AVERAGE:  289970
```

Obviously they should not be negative, but I did run the numbers in excel. These are the results:

var: 31045317.27
std dev: 5571.832488

I can provide more information if needed. 

Thanks in advance.

**Comment by knonomura** [comment]
Thank you for your usage.

I tried your issue, but I couldn't reproduce the similar result.
- Use "date" column as RowKey.
- Store only rows since 1970 year.

I have some comments.
- I guess "COUNT 168" means 14 years.
- Please use griddb.Type.DOUBLE for griddb.Aggregation.STANDARD_DEVIATION.
>stdDev.get(griddb.Type.LONG)


Could you please check the data you stored ?
And could you please provide me more information ?
